import = ["~/.config/alacritty/gruvbox.toml"]

[window]
startup_mode = "Maximized"
title = "maen"

[env]
TERM = "xterm-256color"

[font]
size = 12

normal      = { family = "JetBrains Mono Nerd Font", style = "Regular" }
bold        = { family = "JetBrains Mono Nerd Font", style = "Bold" }
italic      = { family = "JetBrains Mono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrains Mono Nerd Font", style = "Bold Italic" }

[cursor]
style = { shape = "Block", blinking = "Always" }

[selection]
save_to_clipboard = true
