# Gruvbox Color Palette
[colors.primary]
background = "#282828"
foreground = "#ebdbb2"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#282828"
cursor = "#ebdbb2"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.selection]
text = "CellForeground"
background = "#44475a"

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[colors.search.matches]
foreground = "#44475a"
background = "#50fa7b"

[colors.search.focused_match]
foreground = "#44475a"
background = "#ffb86c"

[colors.footer_bar]
background = "#282828"
foreground = "#ebdbb2"

[colors.hints.start]
foreground = "#282828"
background = "#f1fa8c"

[colors.hints.end]
foreground = "#f1fa8c"
background = "#282828"
